### PR TITLE
US004 View Band Level

### PR DESCRIPTION
**Pull request by amchugh689**
- Adds Band Level column to Job Role list
Screenshot 2023-12-14 at 10 27 03

### CODE REVIEW

**Review by Cormac-F — APPROVED** [review]
LGTM

**Review by jkelso662 — CHANGES_REQUESTED** [review]
Very good. Nice small PR. But no tests so I'd recommend use this to add a couple of UI tests.

**Comment by amchugh689** [comment]
i am adding some unit tests to this !

**Comment by amchugh689** [comment]
@jkelso662 @lullabelle hi can you take a look at this please? thanks!

**Review by jkelso662 — APPROVED** [review]
Fab!

**Pull request merged**
