### PR TITLE
US101 - Adding Back Button

### PR DESCRIPTION
**Pull request by CharlesM988**
- Added a back button to the interior pages
- Modified list-jobs.html & view-job-spec.html
- Modified styles.css
- Added a UI test for this addition too

Screenshot 2023-12-20 at 11 53 33
Screenshot 2023-12-20 at 11 53 38 (3)
Screenshot 2023-12-20 at 11 53 51
Screenshot 2023-12-20 at 11 54 00
Screenshot 2023-12-20 at 12 05 36

### CODE REVIEW

**Review by amchugh689 — APPROVED** [review]
tested & working! lgtm

**Comment by jkelso662** [comment]
Can our tech mentors have a look at this demoed before approving please? Stick 15mins in our calendars if you can :)

**Comment by CharlesM988** [comment]
@jkelso662 @lullabelle 

Removed hacky 'back button' and replaced it with a proper breadcrumb navigation.

Screenshot 2023-12-21 at 09 39 21
Screenshot 2023-12-21 at 09 39 29
Screenshot 2023-12-21 at 09 39 38
Screenshot 2023-12-21 at 10 50 39

**Review by jkelso662 — APPROVED** [review]
PR looks good but you have conflicts to sort. Approving as long as they get sorted :)

**Pull request merged**
