### PR TITLE
BL002 - Create UI Repository Skeleton

### PR DESCRIPTION
**Pull request by CharlesM988**
- Added UI skeleton using Node.js.
- Added Express, Nunjucks, Axios and Express-Session as baseline modules.
- Added placeholder index.html file.

- Created yaml file which will use Github actions to build the UI.

Screenshot 2023-12-01 at 11 28 10

Screenshot 2023-12-01 at 11 19 42

### CODE REVIEW

**Comment by jkelso662** [comment]
[like]  Joshua Kelso reacted to your message:
________________________________

**Review by jkelso662 — APPROVED** [review]
It's a yes from me :) 
This PR is to master to remember not to merge until reviewed by PO.

**Comment by CharlesM988** [comment]
> It's a yes from me :) This PR is to master to remember not to merge until reviewed by PO.

We were literally just having this conversation in the group chat!

**Review by Cormac-F — APPROVED** [review]
LGTM.
Add reminder to README file to locally run "npm install" before trying to run :)

**Comment by CharlesM988** [comment]
Added in documentation on how to run the Node application locally and how to run Nodemon.

Updated the yaml, so that Github actions builds for both 'main' & 'ready-for-sign-off' branches.

**Review by jkelso662 — APPROVED** [review]
👍

**Pull request merged**
