### PR TITLE
BL003 - Adding Pull Request Checklist

### PR DESCRIPTION
**Pull request by CharlesM988**
Added in a Pull Request Checklist template in the markdown format.

- Two additional commits to fix some formatting issues that I missed locally.

Screenshot 2023-12-01 at 12 14 06

### CODE REVIEW

**Review by jkelso662 — COMMENTED** [review]
A few things going on here...
1. I can't see that screenshot in the description
2. I can't see ticket BL003 on your board
3. This PR looks like it can be merged already without review... have you enforced branch protection rules on your `ready-for-sign-off` branch?

**Comment by CharlesM988** [comment]
> A few things going on here...
> 
> 1. I can't see that screenshot in the description
> 2. I can't see ticket BL003 on your board
> 3. This PR looks like it can be merged already without review... have you enforced branch protection rules on your `ready-for-sign-off` branch?

@jkelso662 updated the screenshot, turns out a breakline breaks an image. Added BL003 to the ticket board. Will work on branch protection after lunch.

**Review by jkelso662 — APPROVED** [review]
Next review on this repo needs to have branch protection rules enabled. Otherwise I see the other two issues resolved so here's a check we approval to let your tester have a go at this ticket. I'm sure it wont take long to test 😆

**Review by Cormac-F — APPROVED** [review]
LGTM!

**Pull request merged**
